### ISSUE TITLE
Feature Request: support empty GET request.

### ISSUE THREAD

**Issue by anzboi** [connectrpc/grpchealth-go#31]
grpchealth as is provides a pretty convenient up check that could be used for checking whether a server is running. This is pretty useful for kube or docker compose.

Right now, the "minimal" request needed looks like...

```sh
$ curl -X POST http://HOSTNAME/grpc.health.v1.Health/Check -d "{}" -H "Content-Type: application:json"
# 200 OK
```

It would be nice if minimality could be brought down to...
```sh
$ curl -X GET http://HOSTNAME/grpc.health.v1.Health/Check
```

NOTE: Setting `-X GET` causes `405 Method Not Allowed`
Removing the body and content-type causes `415 Unsupported Media Type`

**Comment by akshayjshah** [comment]
Totally understand wanting health checking to be as simple as possible - shorter's better! Even without built-in GET support, I think you can shorten your k8s and Docker compose configurations a fair bit. 

* Kuberbetes [supports gRPC health checks natively](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe) - you don't need to write a `curl` command at all!
* With recent cURL releases (anything more recent than version 7.82.0), you can shorten the command you have above to `curl --json '{}' http://HOSTNAME/grpc.health.v1.Health/Check`. (Note that this command is using the Connect RPC protocol, so it won't work with `grpc-go`, `grpc-java`, etc. servers.)
* The cURL commands you're using are only checking that the HTTP server is up - they're not checking the health of any specific protobuf service. If that's all you care about and you'd prefer to health check with cURL, you don't actually need any of the functionality of this package. Why not simplify and use a standard `GET /health` instead?

```go
func ok(_ http.ResponseWriter, _ *http.Request) {}

func main() {
  mux := http.NewServeMux()
  // mount any other RPC handlers here, and then...
  mux.Handle("/health", http.HandlerFunc(ok))
  http.ListenAndServe(":8080", mux)
}
```

**Comment by solarhell** [comment]
Checked the code and found that if we want to be compatible with http GET, then the changes are significant.

I agree with @akshayjshah  that you can make simplifications in the application code. And the connect-go core lib is still simple.

**Comment by jamesrom** [comment]
It would be nice to be able to hit Check endpoint in the browser and it just work.

**Comment by jhump** [comment]
This repo's purpose is to provide an implementation of the `grpc.health.v1.Health` service, mainly for use with servers that use the `connectrpc.com/connect` module. This is an RPC endpoint, and the definition of the RPC is provided and maintained by [the gRPC organization](https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto). It is not intended to be a general HTTP health-check endpoint.

Wrapping a `grpchealth.Checker` in a simple HTTP GET endpoint is already trivial to do. If that's what you need, you could do something like this in your code:
```go
// HealthEndpoint returns a handler that responds with 200 if the requested
// service is okay and "503 Service Unavailable" otherwise. The service is
// indicated via "service" query parameter. If it is absent, the checker is
// queried with an empty service name. If the checker returns an error
// instead of a status, the result will be "500 Internal Server Error".
func HealthEndpoint(checker grpchealth.Checker) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		resp, err := checker.Check(r.Context(), &grpchealth.CheckRequest{
			Service: r.URL.Query().Get("service"),
		})
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		if resp.Status != grpchealth.StatusServing {
			w.WriteHeader(http.StatusServiceUnavailable)
		} // else, 200 OK status is implied
	})
}
```
But, given the purpose of this repo, that is not really in scope for exported API provided by this module.

**Comment by rorueda** [comment]
This seems to be possible now, by doing this:

```go
mux.Handle(grpchealth.NewHandler(checker, connect.WithIdempotency(connect.IdempotencyNoSideEffects)))
```

Then adding the following query params:

```sh
curl -v 'localhost:8080/grpc.health.v1.Health/Check?encoding=json&message=%7b%7d'
```

For a specific service:

```sh
curl -v 'localhost:8080/grpc.health.v1.Health/Check' --url-query 'encoding=json' --url-query 'message={"service": "my-service"}'
```

PS: It might not be considered an "empty" GET request, but at least it is a GET request.
